name: Django Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use any Python 3.x version available on the runner

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies with pipenv
      run: pipenv install --dev

    - name: Run migrations
      env:
        DATABASE_URL: mysql://user:password@127.0.0.1:3306/test_db
      run: |
        pipenv run python manage.py makemigrations
        pipenv run python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: mysql://user:password@127.0.0.1:3306/test_db
      run: pipenv run python manage.py test
